$schema: ./feed_config.schema.yaml

rss:
  - url: https://blog.waku.org/rss/
  - url: https://github.com/waku-org/go-waku/releases.atom
  - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCAI6Gk0R_1aGa76ShKFA78Q

twitter:
  credentials:
    consumer_key_env: TWITTER_CONSUMER_KEY
    consumer_secret_env: TWITTER_CONSUMER_SECRET
    access_token_env: TWITTER_ACCESS_TOKEN
    access_secret_env: TWITTER_ACCESS_SECRET

  targets:
    - name: Waku_org
      type: profile
    - name: "waku OR libp2p"
      type: search
    - name: waku
      type: hashtag

ethereum:
  - rpc_url: https://rpc.example.com
    contract: 0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85
    event: Transfer(address,address,uint256)
    start_block: 19600000
