// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/broadcast.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// WakuFeedBroadcast is the payload structure sent over Waku
type WakuFeedBroadcast struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ImageData            []byte   `protobuf:"bytes,4,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	MessageHash          []byte   `protobuf:"bytes,5,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	SenderSignature      []byte   `protobuf:"bytes,6,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WakuFeedBroadcast) Reset()         { *m = WakuFeedBroadcast{} }
func (m *WakuFeedBroadcast) String() string { return proto.CompactTextString(m) }
func (*WakuFeedBroadcast) ProtoMessage()    {}
func (*WakuFeedBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{0}
}

func (m *WakuFeedBroadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WakuFeedBroadcast.Unmarshal(m, b)
}
func (m *WakuFeedBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WakuFeedBroadcast.Marshal(b, m, deterministic)
}
func (m *WakuFeedBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WakuFeedBroadcast.Merge(m, src)
}
func (m *WakuFeedBroadcast) XXX_Size() int {
	return xxx_messageInfo_WakuFeedBroadcast.Size(m)
}
func (m *WakuFeedBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_WakuFeedBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_WakuFeedBroadcast proto.InternalMessageInfo

func (m *WakuFeedBroadcast) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WakuFeedBroadcast) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *WakuFeedBroadcast) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *WakuFeedBroadcast) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

func (m *WakuFeedBroadcast) GetMessageHash() []byte {
	if m != nil {
		return m.MessageHash
	}
	return nil
}

func (m *WakuFeedBroadcast) GetSenderSignature() []byte {
	if m != nil {
		return m.SenderSignature
	}
	return nil
}

func init() {
	proto.RegisterType((*WakuFeedBroadcast)(nil), "proto.WakuFeedBroadcast")
}

func init() {
	proto.RegisterFile("proto/broadcast.proto", fileDescriptor_4afaf556da395531)
}

var fileDescriptor_4afaf556da395531 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0xbf, 0x4a, 0xc4, 0x40,
	0x10, 0xc7, 0x71, 0x36, 0x31, 0x81, 0x8c, 0xc1, 0x3f, 0x8b, 0xc2, 0x16, 0x0a, 0xd1, 0x2a, 0x36,
	0x5a, 0xf8, 0x06, 0x22, 0x62, 0x1d, 0x0b, 0xcb, 0x30, 0x71, 0x87, 0x64, 0xf1, 0x36, 0x09, 0x3b,
	0x93, 0x37, 0xbc, 0x07, 0x3b, 0x6e, 0x73, 0xe1, 0xaa, 0xe1, 0xf7, 0xe1, 0xdb, 0x0c, 0xdc, 0xcf,
	0x61, 0x92, 0xe9, 0xad, 0x0b, 0x13, 0xda, 0x3f, 0x64, 0x79, 0x8d, 0x5b, 0x67, 0xf1, 0x3c, 0xef,
	0x15, 0xdc, 0xfe, 0xe2, 0xff, 0xf2, 0x45, 0x64, 0x3f, 0xb6, 0x44, 0x5f, 0x41, 0xe2, 0xac, 0x51,
	0x95, 0xaa, 0x8b, 0x26, 0x71, 0x56, 0xdf, 0x41, 0x26, 0x4e, 0x76, 0x64, 0x92, 0x48, 0xeb, 0xd0,
	0x0f, 0x50, 0x88, 0xf3, 0xc4, 0x82, 0x7e, 0x36, 0x69, 0xa5, 0xea, 0xb4, 0x39, 0x83, 0x7e, 0x04,
	0x70, 0x1e, 0x7b, 0x6a, 0x2d, 0x0a, 0x9a, 0x8b, 0x4a, 0xd5, 0x65, 0x53, 0x44, 0xf9, 0x44, 0x41,
	0xfd, 0x04, 0xa5, 0x27, 0xe6, 0x63, 0x30, 0x20, 0x0f, 0x26, 0x8b, 0xc1, 0xe5, 0xc9, 0xbe, 0x91,
	0x07, 0xfd, 0x02, 0x37, 0x4c, 0xa3, 0xa5, 0xd0, 0xb2, 0xeb, 0x47, 0x94, 0x25, 0x90, 0xc9, 0x63,
	0x76, 0xbd, 0xfa, 0xcf, 0xc6, 0x5d, 0x1e, 0xbf, 0x79, 0x3f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0d,
	0xc6, 0x4c, 0x9b, 0xed, 0x00, 0x00, 0x00,
}
