// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.5
// source: proto/broadcast.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WakuFeedBroadcast is the payload structure sent over Waku.
// It is used to serialize feed items into messages that can be
// transmitted over the Waku network in a verifiable, structured format.
type WakuFeedBroadcast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is a unique identifier for the feed item (e.g., tweet ID, GUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title is a short summary or headline for the feed item.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Timestamp is the Unix time (in seconds) when the item was published.
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Link is the canonical source URL for the content (if available).
	Link string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	// ImageData holds optional raw image bytes (e.g., JPEG/PNG/WebP).
	ImageData []byte `protobuf:"bytes,5,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// MessageHash is a SHA-256 hash of the core message fields.
	MessageHash []byte `protobuf:"bytes,6,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	// SenderSignature is an optional digital signature by the publisher.
	SenderSignature []byte `protobuf:"bytes,7,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WakuFeedBroadcast) Reset() {
	*x = WakuFeedBroadcast{}
	mi := &file_proto_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakuFeedBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakuFeedBroadcast) ProtoMessage() {}

func (x *WakuFeedBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakuFeedBroadcast.ProtoReflect.Descriptor instead.
func (*WakuFeedBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *WakuFeedBroadcast) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WakuFeedBroadcast) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WakuFeedBroadcast) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WakuFeedBroadcast) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *WakuFeedBroadcast) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *WakuFeedBroadcast) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *WakuFeedBroadcast) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

var File_proto_broadcast_proto protoreflect.FileDescriptor

const file_proto_broadcast_proto_rawDesc = "" +
	"\n" +
	"\x15proto/broadcast.proto\x12\x05proto\"\xd8\x01\n" +
	"\x11WakuFeedBroadcast\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"image_data\x18\x05 \x01(\fR\timageData\x12!\n" +
	"\fmessage_hash\x18\x06 \x01(\fR\vmessageHash\x12)\n" +
	"\x10sender_signature\x18\a \x01(\fR\x0fsenderSignatureB+Z)github.com/status-im/cicadian/proto;protob\x06proto3"

var (
	file_proto_broadcast_proto_rawDescOnce sync.Once
	file_proto_broadcast_proto_rawDescData []byte
)

func file_proto_broadcast_proto_rawDescGZIP() []byte {
	file_proto_broadcast_proto_rawDescOnce.Do(func() {
		file_proto_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broadcast_proto_rawDesc), len(file_proto_broadcast_proto_rawDesc)))
	})
	return file_proto_broadcast_proto_rawDescData
}

var file_proto_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_broadcast_proto_goTypes = []any{
	(*WakuFeedBroadcast)(nil), // 0: proto.WakuFeedBroadcast
}
var file_proto_broadcast_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_broadcast_proto_init() }
func file_proto_broadcast_proto_init() {
	if File_proto_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broadcast_proto_rawDesc), len(file_proto_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_broadcast_proto_goTypes,
		DependencyIndexes: file_proto_broadcast_proto_depIdxs,
		MessageInfos:      file_proto_broadcast_proto_msgTypes,
	}.Build()
	File_proto_broadcast_proto = out.File
	file_proto_broadcast_proto_goTypes = nil
	file_proto_broadcast_proto_depIdxs = nil
}
